/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/authenticate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Authenticate a user */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            userName?: string
            password?: string
          }
        }
      }
      responses: {
        /** @description Successful authentication */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              authentication?: string
              userType?: string
            }
          }
        }
        /** @description Invalid user or password */
        401: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/home/users/{userId}/recent-hotels': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get recent hotels for a user */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description User ID */
          userId: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of recent hotels */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': Record<string, never>[]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/home/featured-deals': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get featured hotel deals */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of featured hotel deals */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': Record<string, never>[]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/home/destinations/trending': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get trending destinations */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of trending destinations */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': Record<string, never>[]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/hotels': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get a list of hotels */
    get: {
      parameters: {
        query?: {
          /** @description Search query for filtering hotels */
          searchQuery?: string
          /** @description Page number for pagination */
          pageNumber?: number
          /** @description Number of hotels per page */
          pageSize?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of hotels */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': Record<string, never>[]
          }
        }
      }
    }
    put?: never
    /** Create a new hotel */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': Record<string, never>
        }
      }
      responses: {
        /** @description Hotel created */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/hotels/{id}/gallery': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get hotel gallery by ID */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Hotel ID */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Hotel gallery */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': Record<string, never>[]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/hotels/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get hotel details by ID */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Hotel ID */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Hotel details */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': Record<string, never>
          }
        }
      }
    }
    /** Update a hotel by ID */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Hotel ID */
          id: number
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': Record<string, never>
        }
      }
      responses: {
        /** @description Hotel updated */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    post?: never
    /** Delete a hotel by ID */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Hotel ID */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Hotel deleted */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/hotels/{id}/available-rooms': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get available rooms for a hotel by ID */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Hotel ID */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of available rooms */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': Record<string, never>[]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/hotels/{id}/reviews': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get hotel reviews by ID */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Hotel ID */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of hotel reviews */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': Record<string, never>[]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/bookings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create a booking */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            hotelId?: number
            roomId?: number
            userId?: number
          }
        }
      }
      responses: {
        /** @description Booking confirmation */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': Record<string, never>
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/bookings/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get booking details by ID */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Booking ID */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Booking details */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': Record<string, never>
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/home/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Search for rooms */
    get: {
      parameters: {
        query?: {
          /** @description City for search filter */
          city?: string
          /** @description Check-in date */
          checkInDate?: string
          /** @description Check-out date */
          checkOutDate?: string
          /** @description Number of adults */
          adults?: number
          /** @description Number of children */
          children?: number
          /** @description Number of rooms */
          numberOfRooms?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Search results */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': Record<string, never>[]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/search-results/amenities': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get list of available amenities */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of amenities */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': Record<string, never>[]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/cities': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get list of cities */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of cities */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': Record<string, never>[]
          }
        }
      }
    }
    put?: never
    /** Create a new city */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': Record<string, never>
        }
      }
      responses: {
        /** @description City created */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/hotels/{id}/rooms': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get rooms available in a hotel by ID */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Hotel ID */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of rooms in a hotel */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': Record<string, never>[]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/cities/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Update a city by ID */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description City ID */
          id: number
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': Record<string, never>
        }
      }
      responses: {
        /** @description City updated */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    post?: never
    /** Delete a city by ID */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description City ID */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description City deleted */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/rooms/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Update a room by ID */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Room ID */
          id: number
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': Record<string, never>
        }
      }
      responses: {
        /** @description Room updated */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    post?: never
    /** Delete a room by ID */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Room ID */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Room deleted */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/rooms': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create a new room */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': Record<string, never>
        }
      }
      responses: {
        /** @description Room created */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: never
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
